# Generated by Django 4.2.6 on 2023-11-06 21:08

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.JSONField(default=Product.models.default_subcategory),
        ),
    ]
