# Generated by Django 4.2.6 on 2023-11-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
