# Generated by Django 4.2.6 on 2023-11-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='security_question_pet',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
